"""Generate `astro_brain/data/seed_stars.sql` from the IAU CSN catalogue.

Usage:
    cd backend
    uv run python tools/seed_stars.py --output astro_brain/data/seed_stars.sql

By default pulls https://www.iau.org/static/public/themes/naming_stars/IAU-CSN.txt
and filters to stars with V mag <= 3.0. Pass --input <path> to use a local
fixture instead of the network. Output `.sql` is committed to the repo;
re-running with the same source produces a byte-identical file.
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

CSN_URL = "https://www.iau.org/static/public/themes/naming_stars/IAU-CSN.txt"
DEFAULT_MAX_MAG = 3.0


@dataclass(frozen=True)
class StarRow:
    slug: str
    name: str
    designation: str
    constellation: str
    ra_deg: float
    dec_deg: float
    mag: float


_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(name: str) -> str:
    s = _SLUG_RE.sub("-", name.strip().lower()).strip("-")
    return s


def _parse_float(token: str) -> float | None:
    try:
        return float(token)
    except ValueError:
        return None


_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def parse_csn(text: str) -> list[StarRow]:
    """Parse the IAU CSN whitespace-separated fixed-width format into ``StarRow`` records.

    The real IAU CSN file uses whitespace-separated columns (not pipe-separated).
    Parsing is anchored on the ISO date token (column 15, regex ``YYYY-MM-DD``),
    then fields are read by counting backwards from that anchor:

    - ``date_idx - 1``  → Dec (deg, float)
    - ``date_idx - 2``  → RA (deg, float)
    - ``date_idx - 3``  → HD catalogue number (int or ``_``)
    - ``date_idx - 4``  → HIP catalogue number (int or ``_``)
    - ``date_idx - 5``  → photometric band (single letter, e.g. ``V``)
    - ``date_idx - 6``  → apparent magnitude (float)
    - ``date_idx - 7``  → WDS_J identifier (or ``_``)
    - ``date_idx - 8``  → component letter (e.g. ``A``, ``Aa``, or ``_``)
    - ``date_idx - 9``  → IAU constellation abbreviation (3 letters)
    - ``date_idx - 10`` → Bayer Greek letter (unicode) or ``_``
    - ``date_idx - 11`` → Bayer letter code or ``_``
    - ``tokens[2 .. date_idx - 11]`` → designation (joined with space)
    - ``tokens[0]`` → star name (ASCII)
    - ``tokens[1]`` → star name with diacritics (ignored)

    Lines starting with ``#``, ``$``, or consisting only of whitespace are
    skipped.  Lines whose date token index is ``< 13`` (too few fields) are
    also skipped silently.
    """
    rows: list[StarRow] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("$"):
            continue
        tokens = line.split()
        date_idx = next(
            (i for i, t in enumerate(tokens) if _DATE_RE.match(t)), None
        )
        if date_idx is None or date_idx < 13:
            continue
        name = tokens[0]
        if not name:
            continue
        designation = " ".join(tokens[2 : date_idx - 11]).strip()
        constellation = tokens[date_idx - 9]
        mag = _parse_float(tokens[date_idx - 6])
        ra = _parse_float(tokens[date_idx - 2])
        dec = _parse_float(tokens[date_idx - 1])
        if mag is None or ra is None or dec is None:
            continue
        rows.append(
            StarRow(
                slug=_slugify(name),
                name=name,
                designation=designation,
                constellation=constellation,
                ra_deg=ra,
                dec_deg=dec,
                mag=mag,
            )
        )
    return rows


def _sql_quote(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def build_sql(rows: list[StarRow], *, max_mag: float) -> str:
    """Return a deterministic `.sql` body containing INSERT OR REPLACE rows."""
    keep = sorted(
        (r for r in rows if r.mag <= max_mag and r.slug),
        key=lambda r: r.slug,
    )
    lines: list[str] = [
        "-- Generated by tools/seed_stars.py — DO NOT EDIT BY HAND.",
        f"-- Source: {CSN_URL}",
        f"-- Filter: V mag <= {max_mag}",
        "",
    ]
    for r in keep:
        qid = f"star:{r.slug}"
        lines.append(
            "INSERT OR REPLACE INTO catalog_objects "
            "(id, kind, name, designation, ra_deg, dec_deg, mag, constellation) "
            f"VALUES ({_sql_quote(qid)}, 'star', {_sql_quote(r.name)}, "
            f"{_sql_quote(r.designation)}, {r.ra_deg:.5f}, {r.dec_deg:.5f}, "
            f"{r.mag:.2f}, {_sql_quote(r.constellation)});"
        )
    return "\n".join(lines) + "\n"


def _fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as resp:  # nosec - dev tool
        return resp.read().decode("utf-8", errors="replace")


def main(argv: list[str] | None = None) -> int:
    """Entry point for CLI invocation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="local CSV path (offline mode); defaults to fetching IAU URL",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="output .sql path (e.g. astro_brain/data/seed_stars.sql)",
    )
    parser.add_argument(
        "--max-mag",
        type=float,
        default=DEFAULT_MAX_MAG,
        help=f"cap visible magnitude (default {DEFAULT_MAX_MAG})",
    )
    ns = parser.parse_args(argv)

    text = ns.input.read_text(encoding="utf-8") if ns.input else _fetch(CSN_URL)
    rows = parse_csn(text)
    sql = build_sql(rows, max_mag=ns.max_mag)
    ns.output.parent.mkdir(parents=True, exist_ok=True)
    ns.output.write_text(sql, encoding="utf-8")
    print(f"wrote {len(sql.splitlines())} lines → {ns.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
