"""Generate `astro_brain/data/seed_stars.sql` from the IAU CSN catalogue.

Usage:
    cd backend
    uv run python tools/seed_stars.py --output astro_brain/data/seed_stars.sql

By default pulls https://www.iau.org/static/public/themes/naming_stars/IAU-CSN.txt
and filters to stars with V mag <= 3.0. Pass --input <path> to use a local
fixture instead of the network. Output `.sql` is committed to the repo;
re-running with the same source produces a byte-identical file.
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

CSN_URL = "https://www.iau.org/static/public/themes/naming_stars/IAU-CSN.txt"
DEFAULT_MAX_MAG = 3.0


@dataclass(frozen=True)
class StarRow:
    slug: str
    name: str
    designation: str
    constellation: str
    ra_deg: float
    dec_deg: float
    mag: float


_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(name: str) -> str:
    s = _SLUG_RE.sub("-", name.strip().lower()).strip("-")
    return s


def _parse_float(token: str) -> float | None:
    try:
        return float(token)
    except ValueError:
        return None


def parse_csn(text: str) -> list[StarRow]:
    """Parse the IAU CSN text format into ``StarRow`` records.

    The file is pipe-separated in this codebase's fixtures, with comment lines
    starting with ``#``. Real CSN data is fixed-width — adjust here if the
    upstream format ever differs from the fixture used in tests.
    """
    rows: list[StarRow] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 9:
            continue
        name = parts[0]
        designation = parts[1]
        constellation = parts[4]
        mag = _parse_float(parts[6])
        ra = _parse_float(parts[7])
        dec = _parse_float(parts[8])
        if mag is None or ra is None or dec is None or not name:
            continue
        rows.append(
            StarRow(
                slug=_slugify(name),
                name=name,
                designation=designation,
                constellation=constellation,
                ra_deg=ra,
                dec_deg=dec,
                mag=mag,
            )
        )
    return rows


def _sql_quote(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def build_sql(rows: list[StarRow], *, max_mag: float) -> str:
    """Return a deterministic `.sql` body containing INSERT OR REPLACE rows."""
    keep = sorted(
        (r for r in rows if r.mag <= max_mag and r.slug),
        key=lambda r: r.slug,
    )
    lines: list[str] = [
        "-- Generated by tools/seed_stars.py — DO NOT EDIT BY HAND.",
        f"-- Source: {CSN_URL}",
        f"-- Filter: V mag <= {max_mag}",
        "",
    ]
    for r in keep:
        qid = f"star:{r.slug}"
        lines.append(
            "INSERT OR REPLACE INTO catalog_objects "
            "(id, kind, name, designation, ra_deg, dec_deg, mag, constellation) "
            f"VALUES ({_sql_quote(qid)}, 'star', {_sql_quote(r.name)}, "
            f"{_sql_quote(r.designation)}, {r.ra_deg:.5f}, {r.dec_deg:.5f}, "
            f"{r.mag:.2f}, {_sql_quote(r.constellation)});"
        )
    return "\n".join(lines) + "\n"


def _fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as resp:  # nosec - dev tool
        return resp.read().decode("utf-8", errors="replace")


def main(argv: list[str] | None = None) -> int:
    """Entry point for CLI invocation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="local CSV path (offline mode); defaults to fetching IAU URL",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="output .sql path (e.g. astro_brain/data/seed_stars.sql)",
    )
    parser.add_argument(
        "--max-mag",
        type=float,
        default=DEFAULT_MAX_MAG,
        help=f"cap visible magnitude (default {DEFAULT_MAX_MAG})",
    )
    ns = parser.parse_args(argv)

    text = ns.input.read_text(encoding="utf-8") if ns.input else _fetch(CSN_URL)
    rows = parse_csn(text)
    sql = build_sql(rows, max_mag=ns.max_mag)
    ns.output.parent.mkdir(parents=True, exist_ok=True)
    ns.output.write_text(sql, encoding="utf-8")
    print(f"wrote {len(sql.splitlines())} lines → {ns.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
